# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug_field',
            field=models.SlugField(default='plop'),
            preserve_default=False,
        ),
    ]
