# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 09:14
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170511_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug_field',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='plop', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
